<?php

/**
 * @file
 * Contains redirect_user_login.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function redirect_user_login_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the redirect_user_login module.
    case 'help.page.redirect_user_login':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('redirect user after login') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function redirect_user_login_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Alter login form and add own custom submit handler.
  $form['#submit'][] = '_redirect_user_login_form_submit';
}

/**
 * Custom submit handler for login form.
 */
function _redirect_user_login_form_submit($form, FormStateInterface $form_state) {
  $form_state->setRedirect('<front>');
}